### ISSUE TITLE
Stack list analysis view

### ISSUE THREAD

**Issue by dridk** [labsquare/fastQt#20]
Here is how I made the main view for the next release 0.2. 
tell me what do you thinks ? 

![fastqc_newfeature](https://cloud.githubusercontent.com/assets/1911063/21935206/f542fdf6-d9ac-11e6-8624-fc99f299966e.gif)

**Comment by ikit** [comment]
nice. Ansd when loading is done, how are managed results in the HMI ? 1 tab by file ? Dropdown list ? is it possible to compare files inside a same graph ?

**Comment by dridk** [comment]
You will have to double click on the line to open a new window which display the same view a usual. 
No , I can't compare file inside the same graph for now. And I will not do it  because it's not generic .

**Comment by Arkanosis** [comment]
That's great! :-)

Two things:
  - having all files in the same graph / table (with sortable columns) would be useful, as seeing what's okay, while flattering, is mostly pointless: what people actually need to see first is quality issues / discrepancies in quality between samples using the same techniques;
 - it would be awesome to be able to pass files as parameters on the command line, so that things like `find /path/to/my/fastqs -name '*.fastq.gz' | xargs fastqt` work — that would be much less cumbersome, once you have a few hundreds of samples, than manually selecting files through the file picker.

Keep up the good work!

**Comment by dridk** [comment]
@Arkanosis For the command line arguments we plan to follow same signature than fastqc . So your command will works, but this one too : 

     fastqt fileA.fastq fileB.fastq ...

**Comment by Arkanosis** [comment]
Amazing! :-)

**Comment by natir** [comment]
@Arkanosis see issue #18 and this [wiki page](https://github.com/labsquare/fastQt/wiki/Command%20Line%20Argument) for some information about CLI interface

**Comment by dridk** [comment]
The following design is more common... If you think I miss something... ( Bird will be replace by a file icon with extension type) 

![spectacle j19005](https://cloud.githubusercontent.com/assets/1911063/22314225/c6f0fc2e-e360-11e6-83f7-6fbea4b5507c.png)

**Comment by dridk** [comment]
This is the final test ! It's done!
![newui](https://cloud.githubusercontent.com/assets/1911063/22529911/a4797da0-e8d9-11e6-89c2-6804c1b5d2bb.gif)
