### ISSUE TITLE
Make status for each analysis

### ISSUE THREAD

**Issue by dridk** [labsquare/fastQt#34]
Some analysis hasn't yet status indicator. 
Do it like : https://github.com/labsquare/fastQt/blob/devel/analysis/perbasequalityanalysis.cpp#L205

**Comment by natir** [comment]
I didn't like the idea of status indicator because, a statistic in can be good in one case and not bad in another. A some simple example can be : 
- the length distribution, in pacbio a large standard deviation is normal but in illumina is very strange
- a gc% upper than 70 % can be good in species and not in another.

The status indicator can influence the analysts for a bad reasons.

**Comment by dridk** [comment]
Humm.. You are true.. 
So I suggest to keep only the indicator for the per Base Quality, which is displayed into the Running List view. 
I will remove all other status indicator.

**Comment by natir** [comment]
The level quality can be exceptionally good for pacbio data but very bad for illumina data

**Comment by dridk** [comment]
Actually , only the PerBaseQualtyAnalysis return an icons telling if the analysis are Good, Medium, Bad.

**Comment by natir** [comment]
I still thinking this indicator is a bad feature because can confuse the user.

**Comment by dridk** [comment]
But it's a quality application. We have to notify user with something. 
Actually I remove all status as you said.. But if PerBase Quality analysis have very low quality, I m pretty sure it means the right things for all fastq file.

**Comment by natir** [comment]
We notify the user with something we generate some graph and metrics about data.

The goal of app isn't say this data file is good this data file is bad, the goal is produce metrics and graph to help the analyse (or user) to understand the dataset and say if it's good or not with her knowledge about dataset (biological origin, biochimic routine,  sequencing technologie etc…).

A programme can't say if a dataset is good or not because it's required very important external data.

But if user get some value to fasqt (with conf file ?) fastqt can say this dataset is good/ugly/bad for this metrics. Hard code limit in application is a very very bad idea. The devlopement of conf parser and adaptable status marker isn't a priority for my.
