### ISSUE TITLE
Support of uBAM file

### ISSUE THREAD

**Issue by ikit** [labsquare/fastQt#61]
:+1:

**Comment by natir** [comment]
@ikit Where I can find the uBAM specification format ?

**Comment by natir** [comment]
Wheel,

We can use [bamtools](https://github.com/pezmaster31/bamtools) to read sam, bam and unaligned bam file.

But add this dependency maybe become hard (multi-plateform trouble), I work on this.

**Comment by natir** [comment]
Ok with htslib we can read uBAM file actualy we can detect the BAM file format and open the file. But when I try run analysis, FastQt generate a segfault, I don't know if is my file or is the code. @dridk you know where I can get a standard bamfile ?

**Comment by dridk** [comment]
You can find fastq, bam and vcf file here : http://www.internationalgenome.org/data-portal/sample
Why not using htslib to read bam ?  You can check the code from https://github.com/labsquare/CuteVCF

**Comment by natir** [comment]
@dridk we use htslib to read bam

**Comment by dridk** [comment]
Sorry, I was reading the old mesage with bamtools

**Comment by natir** [comment]
Well,

I think the support of ubam file is ready, I use the quality mapping field for sequence quality.

For test, I convert a fastqt file with this [gatk tutoriel](http://gatkforums.broadinstitute.org/gatk/discussion/6484/how-to-generate-an-unmapped-bam-from-fastq-or-aligned-bam), the result is similar when we use fastqt or ubam.

I want reread code for remove deadcode, no C++ code, and search some bug, but this issue is close to be closed :)

**Comment by natir** [comment]
Ok htslib branch is ready to merge, maybe we need check this branch run on windows before, merging in devel.

We can't have a progression bar for ubam/bam file.

**Comment by natir** [comment]
@dridk @ikit  or other people can check if htslib branch is fully functional and code isn't too ugly.

**Comment by dridk** [comment]
I get unexpected crash with all bam tested : 

![image](https://user-images.githubusercontent.com/1911063/28243429-45848ecc-69c9-11e7-8c73-7a03f47e9b27.png)

**Comment by dridk** [comment]
Don't understand... aln->core.l_qseq return always 0. I tested other parameter like chromosom and position. They works
